name: Deploy Now

on: [push]

jobs:
  deploy-now:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          service-host: api-eu.ionos.space
          project: 22626644-daf5-47e2-a422-163e477d4550
          api-key: ${{ secrets.IONOS_API_KEY }}
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Deploy build
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          storage-quota: ${{ steps.project.outputs.storage-quota }}
          project: 22626644-daf5-47e2-a422-163e477d4550
          dist-folder: ./
          remote-host: ${{ steps.project.outputs.remote-host }}
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          branch-id: ${{ steps.project.outputs.branch-id }}
